import Head from 'next/head'
import conectarDB from '../lib/dbConnect'
import Movie from '../models/Movie'


export default function Home({movies}) {
  console.log(movies)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container' >
        <h1>Movies</h1>
      </main>
     </div>
  )

}

export async function getServerSideProps(){
    try {
        await conectarDB()
        const res= await Movie.find({})

        const movies=res.map(doc=>{
          const movie=doc.toObject() 
          movie._id=`${movie._id}`
          return movie
        })
        console.log(res)
        return {props:{movies:123}}
    } catch (error) {
      console.log(error)
    }
}
